#############################################################################
# Makefile for building: Панель управления пользователями РЛС ТИ версия 47
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  users.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile users.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050B00 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Панель управления пользователями РЛС ТИ версия 471.0.0
DISTDIR = /home/user/users.10/.tmp/Панель управления пользователями РЛС ТИ версия 471.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Services/integrityservice.cpp \
		User_GUI/User_GUI.cpp \
		Admin_GUI/Model/usermodel.cpp \
		Admin_GUI/Model/sortmodel.cpp \
		Admin_GUI/Delegates/userdelegate.cpp \
		Admin_GUI/Views/qtoast.cpp \
		lib/qtmaterialstyle.cpp \
		lib/qtmaterialtheme.cpp \
		lib/qtmaterialoverlaywidget.cpp \
		lib/qtmaterialcheckable_internal.cpp \
		lib/qtmaterialcheckable.cpp \
		lib/qtmaterialripple.cpp \
		lib/qtmaterialrippleoverlay.cpp \
		lib/qtmaterialstatetransition.cpp \
		Admin_GUI/Widgets/qtmaterialtextfield_internal.cpp \
		Admin_GUI/Widgets/qtmaterialtextfield.cpp \
		Admin_GUI/Widgets/qtmaterialtoggle_internal.cpp \
		Admin_GUI/Widgets/qtmaterialtoggle.cpp \
		Admin_GUI/Widgets/qtmaterialdialog_internal.cpp \
		Admin_GUI/Widgets/qtmaterialdialog.cpp \
		Admin_GUI/Views/filedialogwidget.cpp \
		Services/terminal.cpp \
		Services/fileexplorer.cpp \
		Services/kioskservice.cpp \
		Services/databaseservice.cpp \
		Services/linuxuserservice.cpp \
		Services/identifyservice.cpp \
		Services/toolbardisableservice.cpp \
		Admin_GUI/Views/desktoppanel.cpp \
		Admin_GUI/Views/roleeditpanel.cpp \
		Admin_GUI/Views/additionalsettingspanel.cpp \
		Admin_GUI/Views/userfileseditpanel.cpp \
		Admin_GUI/Views/topbar.cpp \
		Admin_GUI/Views/startuppanel.cpp \
		Admin_GUI/Delegates/filedelegate.cpp \
		Admin_GUI/Views/admingui.cpp \
		Admin_GUI/Views/linuxuserslistwidget.cpp \
		Admin_GUI/Views/userinfopanel.cpp \
		Admin_GUI/Views/usereditpanel.cpp \
		Admin_GUI/Views/settingspanel.cpp \
		Services/startuprepositoryservice.cpp \
		Services/startuprunnableservice.cpp \
		Server/messagesrepository.cpp \
		Server/dataHandler.cpp \
		program.cpp \
		Admin_GUI/Views/startupdialogwidget.cpp \
		Admin_GUI/Widgets/popupdialog.cpp \
		globalfunctions.cpp \
		Services/appsettingsservice.cpp \
		Styles/darkstyle.cpp \
		Styles/framelesswindow.cpp \
		Styles/windowdragger.cpp qrc_resources.cpp \
		moc_User_GUI.cpp \
		moc_usermodel.cpp \
		moc_sortmodel.cpp \
		moc_qtoast.cpp \
		moc_qtmaterialstyle.cpp \
		moc_qtmaterialtheme.cpp \
		moc_qtmaterialoverlaywidget.cpp \
		moc_qtmaterialcheckable_internal.cpp \
		moc_qtmaterialripple.cpp \
		moc_qtmaterialrippleoverlay.cpp \
		moc_qtmaterialcheckable.cpp \
		moc_qtmaterialstatetransition.cpp \
		moc_qtmaterialtextfield_internal.cpp \
		moc_qtmaterialtextfield.cpp \
		moc_qtmaterialtoggle_internal.cpp \
		moc_qtmaterialtoggle.cpp \
		moc_qtmaterialdialog_internal.cpp \
		moc_qtmaterialdialog.cpp \
		moc_filedialogwidget.cpp \
		moc_desktoppanel.cpp \
		moc_roleeditpanel.cpp \
		moc_additionalsettingspanel.cpp \
		moc_userfileseditpanel.cpp \
		moc_topbar.cpp \
		moc_startuppanel.cpp \
		moc_admingui.cpp \
		moc_linuxuserslistwidget.cpp \
		moc_userinfopanel.cpp \
		moc_usereditpanel.cpp \
		moc_settingspanel.cpp \
		moc_startuprunnableservice.cpp \
		moc_dataHandler.cpp \
		moc_program.cpp \
		moc_startupdialogwidget.cpp \
		moc_popupdialog.cpp \
		moc_darkstyle.cpp \
		moc_framelesswindow.cpp \
		moc_windowdragger.cpp
OBJECTS       = main.o \
		integrityservice.o \
		User_GUI.o \
		usermodel.o \
		sortmodel.o \
		userdelegate.o \
		qtoast.o \
		qtmaterialstyle.o \
		qtmaterialtheme.o \
		qtmaterialoverlaywidget.o \
		qtmaterialcheckable_internal.o \
		qtmaterialcheckable.o \
		qtmaterialripple.o \
		qtmaterialrippleoverlay.o \
		qtmaterialstatetransition.o \
		qtmaterialtextfield_internal.o \
		qtmaterialtextfield.o \
		qtmaterialtoggle_internal.o \
		qtmaterialtoggle.o \
		qtmaterialdialog_internal.o \
		qtmaterialdialog.o \
		filedialogwidget.o \
		terminal.o \
		fileexplorer.o \
		kioskservice.o \
		databaseservice.o \
		linuxuserservice.o \
		identifyservice.o \
		toolbardisableservice.o \
		desktoppanel.o \
		roleeditpanel.o \
		additionalsettingspanel.o \
		userfileseditpanel.o \
		topbar.o \
		startuppanel.o \
		filedelegate.o \
		admingui.o \
		linuxuserslistwidget.o \
		userinfopanel.o \
		usereditpanel.o \
		settingspanel.o \
		startuprepositoryservice.o \
		startuprunnableservice.o \
		messagesrepository.o \
		dataHandler.o \
		program.o \
		startupdialogwidget.o \
		popupdialog.o \
		globalfunctions.o \
		appsettingsservice.o \
		darkstyle.o \
		framelesswindow.o \
		windowdragger.o \
		qrc_resources.o \
		moc_User_GUI.o \
		moc_usermodel.o \
		moc_sortmodel.o \
		moc_qtoast.o \
		moc_qtmaterialstyle.o \
		moc_qtmaterialtheme.o \
		moc_qtmaterialoverlaywidget.o \
		moc_qtmaterialcheckable_internal.o \
		moc_qtmaterialripple.o \
		moc_qtmaterialrippleoverlay.o \
		moc_qtmaterialcheckable.o \
		moc_qtmaterialstatetransition.o \
		moc_qtmaterialtextfield_internal.o \
		moc_qtmaterialtextfield.o \
		moc_qtmaterialtoggle_internal.o \
		moc_qtmaterialtoggle.o \
		moc_qtmaterialdialog_internal.o \
		moc_qtmaterialdialog.o \
		moc_filedialogwidget.o \
		moc_desktoppanel.o \
		moc_roleeditpanel.o \
		moc_additionalsettingspanel.o \
		moc_userfileseditpanel.o \
		moc_topbar.o \
		moc_startuppanel.o \
		moc_admingui.o \
		moc_linuxuserslistwidget.o \
		moc_userinfopanel.o \
		moc_usereditpanel.o \
		moc_settingspanel.o \
		moc_startuprunnableservice.o \
		moc_dataHandler.o \
		moc_program.o \
		moc_startupdialogwidget.o \
		moc_popupdialog.o \
		moc_darkstyle.o \
		moc_framelesswindow.o \
		moc_windowdragger.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		users.pro User_GUI/User_GUI.h \
		Services/integrityservice.h \
		Structs/userstruct.h \
		Structs/programstruct.h \
		Admin_GUI/Model/usermodel.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Delegates/userdelegate.h \
		Admin_GUI/Views/qtoast.h \
		lib/qtmaterialstyle_p.h \
		lib/qtmaterialstyle.h \
		lib/qtmaterialtheme_p.h \
		lib/qtmaterialtheme.h \
		lib/qtmaterialoverlaywidget.h \
		lib/qtmaterialcheckable_internal.h \
		lib/qtmaterialcheckable_p.h \
		lib/qtmaterialripple.h \
		lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialcheckable.h \
		lib/qtmaterialstatetransition.h \
		lib/qtmaterialstatetransitionevent.h \
		Admin_GUI/Widgets/qtmaterialtextfield_internal.h \
		Admin_GUI/Widgets/qtmaterialtextfield_p.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle_internal.h \
		Admin_GUI/Widgets/qtmaterialtoggle_p.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Widgets/qtmaterialdialog_internal.h \
		Admin_GUI/Widgets/qtmaterialdialog_p.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		Admin_GUI/Views/filedialogwidget.h \
		Services/terminal.h \
		Services/fileexplorer.h \
		Services/kioskservice.h \
		Services/databaseservice.h \
		Services/linuxuserservice.h \
		Services/identifyservice.h \
		Services/toolbardisableservice.h \
		Admin_GUI/Views/desktoppanel.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		Admin_GUI/Views/userfileseditpanel.h \
		Admin_GUI/Views/topbar.h \
		Admin_GUI/Views/startuppanel.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Views/admingui.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Views/userinfopanel.h \
		Admin_GUI/Views/usereditpanel.h \
		Admin_GUI/Views/settingspanel.h \
		Services/startuprepositoryservice.h \
		Services/startuprunnableservice.h \
		Server/DataMessage.h \
		Server/messagesrepository.h \
		Server/dataHandler.h \
		program.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Widgets/popupdialog.h \
		globalfunctions.h \
		Services/appsettingsservice.h \
		Styles/darkstyle.h \
		Styles/framelesswindow.h \
		Styles/windowdragger.h main.cpp \
		Services/integrityservice.cpp \
		User_GUI/User_GUI.cpp \
		Admin_GUI/Model/usermodel.cpp \
		Admin_GUI/Model/sortmodel.cpp \
		Admin_GUI/Delegates/userdelegate.cpp \
		Admin_GUI/Views/qtoast.cpp \
		lib/qtmaterialstyle.cpp \
		lib/qtmaterialtheme.cpp \
		lib/qtmaterialoverlaywidget.cpp \
		lib/qtmaterialcheckable_internal.cpp \
		lib/qtmaterialcheckable.cpp \
		lib/qtmaterialripple.cpp \
		lib/qtmaterialrippleoverlay.cpp \
		lib/qtmaterialstatetransition.cpp \
		Admin_GUI/Widgets/qtmaterialtextfield_internal.cpp \
		Admin_GUI/Widgets/qtmaterialtextfield.cpp \
		Admin_GUI/Widgets/qtmaterialtoggle_internal.cpp \
		Admin_GUI/Widgets/qtmaterialtoggle.cpp \
		Admin_GUI/Widgets/qtmaterialdialog_internal.cpp \
		Admin_GUI/Widgets/qtmaterialdialog.cpp \
		Admin_GUI/Views/filedialogwidget.cpp \
		Services/terminal.cpp \
		Services/fileexplorer.cpp \
		Services/kioskservice.cpp \
		Services/databaseservice.cpp \
		Services/linuxuserservice.cpp \
		Services/identifyservice.cpp \
		Services/toolbardisableservice.cpp \
		Admin_GUI/Views/desktoppanel.cpp \
		Admin_GUI/Views/roleeditpanel.cpp \
		Admin_GUI/Views/additionalsettingspanel.cpp \
		Admin_GUI/Views/userfileseditpanel.cpp \
		Admin_GUI/Views/topbar.cpp \
		Admin_GUI/Views/startuppanel.cpp \
		Admin_GUI/Delegates/filedelegate.cpp \
		Admin_GUI/Views/admingui.cpp \
		Admin_GUI/Views/linuxuserslistwidget.cpp \
		Admin_GUI/Views/userinfopanel.cpp \
		Admin_GUI/Views/usereditpanel.cpp \
		Admin_GUI/Views/settingspanel.cpp \
		Services/startuprepositoryservice.cpp \
		Services/startuprunnableservice.cpp \
		Server/messagesrepository.cpp \
		Server/dataHandler.cpp \
		program.cpp \
		Admin_GUI/Views/startupdialogwidget.cpp \
		Admin_GUI/Widgets/popupdialog.cpp \
		globalfunctions.cpp \
		Services/appsettingsservice.cpp \
		Styles/darkstyle.cpp \
		Styles/framelesswindow.cpp \
		Styles/windowdragger.cpp
QMAKE_TARGET  = Панель управления пользователями РЛС ТИ версия 47
DESTDIR       = 
TARGET        = Панель управления пользователями РЛС ТИ версия 47


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: users.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		users.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile users.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
users.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile users.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents User_GUI/User_GUI.h Services/integrityservice.h Structs/userstruct.h Structs/programstruct.h Admin_GUI/Model/usermodel.h Admin_GUI/Model/sortmodel.h Admin_GUI/Delegates/userdelegate.h Admin_GUI/Views/qtoast.h lib/qtmaterialstyle_p.h lib/qtmaterialstyle.h lib/qtmaterialtheme_p.h lib/qtmaterialtheme.h lib/qtmaterialoverlaywidget.h lib/qtmaterialcheckable_internal.h lib/qtmaterialcheckable_p.h lib/qtmaterialripple.h lib/qtmaterialrippleoverlay.h lib/qtmaterialcheckable.h lib/qtmaterialstatetransition.h lib/qtmaterialstatetransitionevent.h Admin_GUI/Widgets/qtmaterialtextfield_internal.h Admin_GUI/Widgets/qtmaterialtextfield_p.h Admin_GUI/Widgets/qtmaterialtextfield.h Admin_GUI/Widgets/qtmaterialtoggle_internal.h Admin_GUI/Widgets/qtmaterialtoggle_p.h Admin_GUI/Widgets/qtmaterialtoggle.h Admin_GUI/Widgets/qtmaterialdialog_internal.h Admin_GUI/Widgets/qtmaterialdialog_p.h Admin_GUI/Widgets/qtmaterialdialog.h Admin_GUI/Views/filedialogwidget.h Services/terminal.h Services/fileexplorer.h Services/kioskservice.h Services/databaseservice.h Services/linuxuserservice.h Services/identifyservice.h Services/toolbardisableservice.h Admin_GUI/Views/desktoppanel.h Admin_GUI/Views/roleeditpanel.h Admin_GUI/Views/additionalsettingspanel.h Admin_GUI/Views/userfileseditpanel.h Admin_GUI/Views/topbar.h Admin_GUI/Views/startuppanel.h Admin_GUI/Delegates/filedelegate.h Admin_GUI/Views/admingui.h Admin_GUI/Views/linuxuserslistwidget.h Admin_GUI/Views/userinfopanel.h Admin_GUI/Views/usereditpanel.h Admin_GUI/Views/settingspanel.h Services/startuprepositoryservice.h Services/startuprunnableservice.h Server/DataMessage.h Server/messagesrepository.h Server/dataHandler.h program.h Admin_GUI/Views/startupdialogwidget.h Admin_GUI/Widgets/popupdialog.h globalfunctions.h Services/appsettingsservice.h Styles/darkstyle.h Styles/framelesswindow.h Styles/windowdragger.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Services/integrityservice.cpp User_GUI/User_GUI.cpp Admin_GUI/Model/usermodel.cpp Admin_GUI/Model/sortmodel.cpp Admin_GUI/Delegates/userdelegate.cpp Admin_GUI/Views/qtoast.cpp lib/qtmaterialstyle.cpp lib/qtmaterialtheme.cpp lib/qtmaterialoverlaywidget.cpp lib/qtmaterialcheckable_internal.cpp lib/qtmaterialcheckable.cpp lib/qtmaterialripple.cpp lib/qtmaterialrippleoverlay.cpp lib/qtmaterialstatetransition.cpp Admin_GUI/Widgets/qtmaterialtextfield_internal.cpp Admin_GUI/Widgets/qtmaterialtextfield.cpp Admin_GUI/Widgets/qtmaterialtoggle_internal.cpp Admin_GUI/Widgets/qtmaterialtoggle.cpp Admin_GUI/Widgets/qtmaterialdialog_internal.cpp Admin_GUI/Widgets/qtmaterialdialog.cpp Admin_GUI/Views/filedialogwidget.cpp Services/terminal.cpp Services/fileexplorer.cpp Services/kioskservice.cpp Services/databaseservice.cpp Services/linuxuserservice.cpp Services/identifyservice.cpp Services/toolbardisableservice.cpp Admin_GUI/Views/desktoppanel.cpp Admin_GUI/Views/roleeditpanel.cpp Admin_GUI/Views/additionalsettingspanel.cpp Admin_GUI/Views/userfileseditpanel.cpp Admin_GUI/Views/topbar.cpp Admin_GUI/Views/startuppanel.cpp Admin_GUI/Delegates/filedelegate.cpp Admin_GUI/Views/admingui.cpp Admin_GUI/Views/linuxuserslistwidget.cpp Admin_GUI/Views/userinfopanel.cpp Admin_GUI/Views/usereditpanel.cpp Admin_GUI/Views/settingspanel.cpp Services/startuprepositoryservice.cpp Services/startuprunnableservice.cpp Server/messagesrepository.cpp Server/dataHandler.cpp program.cpp Admin_GUI/Views/startupdialogwidget.cpp Admin_GUI/Widgets/popupdialog.cpp globalfunctions.cpp Services/appsettingsservice.cpp Styles/darkstyle.cpp Styles/framelesswindow.cpp Styles/windowdragger.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		images/ico.png \
		images/0.jpg \
		images/hover.ico \
		images/next.ico \
		images/3.jpg \
		images/settings2.ico \
		images/2.jpg \
		images/settings.ico \
		images/1.jpg \
		images/widgets-icons/icon_checkbox_indeterminate_disabled.png \
		images/widgets-icons/icon_checkbox_indeterminate_pressed.png \
		images/widgets-icons/icon_vline.png \
		images/widgets-icons/icon_window_close.png \
		images/widgets-icons/icon_branch_open.png \
		images/widgets-icons/icon_radiobutton_checked_pressed.png \
		images/widgets-icons/icon_checkbox_checked.png \
		images/widgets-icons/icon_close.png \
		images/widgets-icons/icon_checkbox_checked_disabled.png \
		images/widgets-icons/icon_checkbox_checked_pressed.png \
		images/widgets-icons/icon_radiobutton_checked_disabled.png \
		images/widgets-icons/icon_restore.png \
		images/widgets-icons/icon_checkbox_unchecked_disabled.png \
		images/widgets-icons/icon_radiobutton_unchecked_pressed.png \
		images/widgets-icons/icon_radiobutton_unchecked.png \
		images/widgets-icons/icon_undock.png \
		images/widgets-icons/icon_branch_end.png \
		images/widgets-icons/icon_checkbox_indeterminate.png \
		images/widgets-icons/icon_window_minimize.png \
		images/widgets-icons/icon_window_restore.png \
		images/widgets-icons/icon_window_maximize.png \
		images/widgets-icons/icon_checkbox_unchecked_pressed.png \
		images/widgets-icons/icon_branch_closed.png \
		images/widgets-icons/icon_radiobutton_checked.png \
		images/widgets-icons/icon_radiobutton_unchecked_disabled.png \
		images/widgets-icons/icon_branch_more.png \
		images/widgets-icons/icon_checkbox_unchecked.png \
		Styles/style.qss \
		fonts/font.ttf
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_User_GUI.cpp moc_usermodel.cpp moc_sortmodel.cpp moc_qtoast.cpp moc_qtmaterialstyle.cpp moc_qtmaterialtheme.cpp moc_qtmaterialoverlaywidget.cpp moc_qtmaterialcheckable_internal.cpp moc_qtmaterialripple.cpp moc_qtmaterialrippleoverlay.cpp moc_qtmaterialcheckable.cpp moc_qtmaterialstatetransition.cpp moc_qtmaterialtextfield_internal.cpp moc_qtmaterialtextfield.cpp moc_qtmaterialtoggle_internal.cpp moc_qtmaterialtoggle.cpp moc_qtmaterialdialog_internal.cpp moc_qtmaterialdialog.cpp moc_filedialogwidget.cpp moc_desktoppanel.cpp moc_roleeditpanel.cpp moc_additionalsettingspanel.cpp moc_userfileseditpanel.cpp moc_topbar.cpp moc_startuppanel.cpp moc_admingui.cpp moc_linuxuserslistwidget.cpp moc_userinfopanel.cpp moc_usereditpanel.cpp moc_settingspanel.cpp moc_startuprunnableservice.cpp moc_dataHandler.cpp moc_program.cpp moc_startupdialogwidget.cpp moc_popupdialog.cpp moc_darkstyle.cpp moc_framelesswindow.cpp moc_windowdragger.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_User_GUI.cpp moc_usermodel.cpp moc_sortmodel.cpp moc_qtoast.cpp moc_qtmaterialstyle.cpp moc_qtmaterialtheme.cpp moc_qtmaterialoverlaywidget.cpp moc_qtmaterialcheckable_internal.cpp moc_qtmaterialripple.cpp moc_qtmaterialrippleoverlay.cpp moc_qtmaterialcheckable.cpp moc_qtmaterialstatetransition.cpp moc_qtmaterialtextfield_internal.cpp moc_qtmaterialtextfield.cpp moc_qtmaterialtoggle_internal.cpp moc_qtmaterialtoggle.cpp moc_qtmaterialdialog_internal.cpp moc_qtmaterialdialog.cpp moc_filedialogwidget.cpp moc_desktoppanel.cpp moc_roleeditpanel.cpp moc_additionalsettingspanel.cpp moc_userfileseditpanel.cpp moc_topbar.cpp moc_startuppanel.cpp moc_admingui.cpp moc_linuxuserslistwidget.cpp moc_userinfopanel.cpp moc_usereditpanel.cpp moc_settingspanel.cpp moc_startuprunnableservice.cpp moc_dataHandler.cpp moc_program.cpp moc_startupdialogwidget.cpp moc_popupdialog.cpp moc_darkstyle.cpp moc_framelesswindow.cpp moc_windowdragger.cpp
moc_User_GUI.cpp: User_GUI/User_GUI.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include User_GUI/User_GUI.h -o moc_User_GUI.cpp

moc_usermodel.cpp: Structs/userstruct.h \
		Services/linuxuserservice.h \
		Services/terminal.h \
		Services/databaseservice.h \
		Admin_GUI/Model/usermodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Model/usermodel.h -o moc_usermodel.cpp

moc_sortmodel.cpp: Structs/userstruct.h \
		Admin_GUI/Model/sortmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Model/sortmodel.h -o moc_sortmodel.cpp

moc_qtoast.cpp: Admin_GUI/Views/qtoast.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/qtoast.h -o moc_qtoast.cpp

moc_qtmaterialstyle.cpp: lib/qtmaterialstyle_p.h \
		lib/qtmaterialstyle.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialstyle.h -o moc_qtmaterialstyle.cpp

moc_qtmaterialtheme.cpp: lib/qtmaterialtheme.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialtheme.h -o moc_qtmaterialtheme.cpp

moc_qtmaterialoverlaywidget.cpp: lib/qtmaterialoverlaywidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialoverlaywidget.h -o moc_qtmaterialoverlaywidget.cpp

moc_qtmaterialcheckable_internal.cpp: lib/qtmaterialcheckable_internal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialcheckable_internal.h -o moc_qtmaterialcheckable_internal.cpp

moc_qtmaterialripple.cpp: lib/qtmaterialripple.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialripple.h -o moc_qtmaterialripple.cpp

moc_qtmaterialrippleoverlay.cpp: lib/qtmaterialoverlaywidget.h \
		lib/qtmaterialrippleoverlay.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialrippleoverlay.h -o moc_qtmaterialrippleoverlay.cpp

moc_qtmaterialcheckable.cpp: lib/qtmaterialcheckable.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialcheckable.h -o moc_qtmaterialcheckable.cpp

moc_qtmaterialstatetransition.cpp: lib/qtmaterialstatetransitionevent.h \
		lib/qtmaterialstatetransition.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/qtmaterialstatetransition.h -o moc_qtmaterialstatetransition.cpp

moc_qtmaterialtextfield_internal.cpp: Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtextfield_internal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/qtmaterialtextfield_internal.h -o moc_qtmaterialtextfield_internal.cpp

moc_qtmaterialtextfield.cpp: Admin_GUI/Widgets/qtmaterialtextfield.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/qtmaterialtextfield.h -o moc_qtmaterialtextfield.cpp

moc_qtmaterialtoggle_internal.cpp: lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Widgets/qtmaterialtoggle_internal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/qtmaterialtoggle_internal.h -o moc_qtmaterialtoggle_internal.cpp

moc_qtmaterialtoggle.cpp: Admin_GUI/Widgets/qtmaterialtoggle.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/qtmaterialtoggle.h -o moc_qtmaterialtoggle.cpp

moc_qtmaterialdialog_internal.cpp: Admin_GUI/Widgets/qtmaterialdialog_internal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/qtmaterialdialog_internal.h -o moc_qtmaterialdialog_internal.cpp

moc_qtmaterialdialog.cpp: lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/qtmaterialdialog.h -o moc_qtmaterialdialog.cpp

moc_filedialogwidget.cpp: globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/filedialogwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/filedialogwidget.h -o moc_filedialogwidget.cpp

moc_desktoppanel.cpp: Structs/programstruct.h \
		Services/fileexplorer.h \
		Services/terminal.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/desktoppanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/desktoppanel.h -o moc_desktoppanel.cpp

moc_roleeditpanel.cpp: Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Services/terminal.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/roleeditpanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/roleeditpanel.h -o moc_roleeditpanel.cpp

moc_additionalsettingspanel.cpp: Services/linuxuserservice.h \
		Services/terminal.h \
		Structs/userstruct.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/additionalsettingspanel.h -o moc_additionalsettingspanel.cpp

moc_userfileseditpanel.cpp: Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Services/terminal.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/userfileseditpanel.h -o moc_userfileseditpanel.cpp

moc_topbar.cpp: Admin_GUI/Views/topbar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/topbar.h -o moc_topbar.cpp

moc_startuppanel.cpp: Services/startuprepositoryservice.h \
		Services/terminal.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/startuppanel.h -o moc_startuppanel.cpp

moc_admingui.cpp: Services/databaseservice.h \
		Structs/userstruct.h \
		Services/terminal.h \
		Services/linuxuserservice.h \
		Admin_GUI/Model/usermodel.h \
		Admin_GUI/Views/topbar.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Delegates/userdelegate.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Views/settingspanel.h \
		Admin_GUI/Views/userinfopanel.h \
		Services/integrityservice.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h \
		Admin_GUI/Views/admingui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/admingui.h -o moc_admingui.cpp

moc_linuxuserslistwidget.cpp: Admin_GUI/Delegates/userdelegate.h \
		Structs/userstruct.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Model/usermodel.h \
		Services/linuxuserservice.h \
		Services/terminal.h \
		Services/databaseservice.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/linuxuserslistwidget.h -o moc_linuxuserslistwidget.cpp

moc_userinfopanel.cpp: Structs/userstruct.h \
		Services/integrityservice.h \
		Services/terminal.h \
		Admin_GUI/Views/userinfopanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/userinfopanel.h -o moc_userinfopanel.cpp

moc_usereditpanel.cpp: Services/databaseservice.h \
		Structs/userstruct.h \
		Services/terminal.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/usereditpanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/usereditpanel.h -o moc_usereditpanel.cpp

moc_settingspanel.cpp: Admin_GUI/Views/userinfopanel.h \
		Structs/userstruct.h \
		Services/integrityservice.h \
		Services/terminal.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/databaseservice.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/settingspanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/settingspanel.h -o moc_settingspanel.cpp

moc_startuprunnableservice.cpp: Services/terminal.h \
		Services/startuprunnableservice.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Services/startuprunnableservice.h -o moc_startuprunnableservice.cpp

moc_dataHandler.cpp: Server/messagesrepository.h \
		Server/DataMessage.h \
		Server/dataHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Server/dataHandler.h -o moc_dataHandler.cpp

moc_program.cpp: Services/appsettingsservice.h \
		globalfunctions.h \
		Services/terminal.h \
		Services/identifyservice.h \
		Services/databaseservice.h \
		Structs/userstruct.h \
		Services/linuxuserservice.h \
		Services/toolbardisableservice.h \
		Services/startuprunnableservice.h \
		Server/dataHandler.h \
		Server/messagesrepository.h \
		Server/DataMessage.h \
		Admin_GUI/Views/admingui.h \
		Admin_GUI/Model/usermodel.h \
		Admin_GUI/Views/topbar.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Delegates/userdelegate.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Views/settingspanel.h \
		Admin_GUI/Views/userinfopanel.h \
		Services/integrityservice.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h \
		User_GUI/User_GUI.h \
		Styles/framelesswindow.h \
		Styles/windowdragger.h \
		Styles/darkstyle.h \
		program.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include program.h -o moc_program.cpp

moc_startupdialogwidget.cpp: Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startupdialogwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Views/startupdialogwidget.h -o moc_startupdialogwidget.cpp

moc_popupdialog.cpp: Admin_GUI/Widgets/popupdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Admin_GUI/Widgets/popupdialog.h -o moc_popupdialog.cpp

moc_darkstyle.cpp: Styles/darkstyle.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Styles/darkstyle.h -o moc_darkstyle.cpp

moc_framelesswindow.cpp: Styles/windowdragger.h \
		Styles/framelesswindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Styles/framelesswindow.h -o moc_framelesswindow.cpp

moc_windowdragger.cpp: Styles/windowdragger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/user/users.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Styles/windowdragger.h -o moc_windowdragger.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp program.h \
		Services/appsettingsservice.h \
		globalfunctions.h \
		Services/terminal.h \
		Services/identifyservice.h \
		Services/databaseservice.h \
		Structs/userstruct.h \
		Services/linuxuserservice.h \
		Services/toolbardisableservice.h \
		Services/startuprunnableservice.h \
		Server/dataHandler.h \
		Server/messagesrepository.h \
		Server/DataMessage.h \
		Admin_GUI/Views/admingui.h \
		Admin_GUI/Model/usermodel.h \
		Admin_GUI/Views/topbar.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Delegates/userdelegate.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Views/settingspanel.h \
		Admin_GUI/Views/userinfopanel.h \
		Services/integrityservice.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h \
		User_GUI/User_GUI.h \
		Styles/framelesswindow.h \
		Styles/windowdragger.h \
		Styles/darkstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

integrityservice.o: Services/integrityservice.cpp Services/integrityservice.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integrityservice.o Services/integrityservice.cpp

User_GUI.o: User_GUI/User_GUI.cpp User_GUI/User_GUI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User_GUI.o User_GUI/User_GUI.cpp

usermodel.o: Admin_GUI/Model/usermodel.cpp Admin_GUI/Model/usermodel.h \
		Structs/userstruct.h \
		Services/linuxuserservice.h \
		Services/terminal.h \
		Services/databaseservice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermodel.o Admin_GUI/Model/usermodel.cpp

sortmodel.o: Admin_GUI/Model/sortmodel.cpp Admin_GUI/Model/sortmodel.h \
		Structs/userstruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sortmodel.o Admin_GUI/Model/sortmodel.cpp

userdelegate.o: Admin_GUI/Delegates/userdelegate.cpp Admin_GUI/Delegates/userdelegate.h \
		Structs/userstruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userdelegate.o Admin_GUI/Delegates/userdelegate.cpp

qtoast.o: Admin_GUI/Views/qtoast.cpp Admin_GUI/Views/qtoast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtoast.o Admin_GUI/Views/qtoast.cpp

qtmaterialstyle.o: lib/qtmaterialstyle.cpp lib/qtmaterialstyle.h \
		lib/qtmaterialstyle_p.h \
		lib/qtmaterialtheme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialstyle.o lib/qtmaterialstyle.cpp

qtmaterialtheme.o: lib/qtmaterialtheme.cpp lib/qtmaterialtheme.h \
		lib/qtmaterialtheme_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialtheme.o lib/qtmaterialtheme.cpp

qtmaterialoverlaywidget.o: lib/qtmaterialoverlaywidget.cpp lib/qtmaterialoverlaywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialoverlaywidget.o lib/qtmaterialoverlaywidget.cpp

qtmaterialcheckable_internal.o: lib/qtmaterialcheckable_internal.cpp lib/qtmaterialcheckable_internal.h \
		lib/qtmaterialcheckable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialcheckable_internal.o lib/qtmaterialcheckable_internal.cpp

qtmaterialcheckable.o: lib/qtmaterialcheckable.cpp lib/qtmaterialcheckable.h \
		lib/qtmaterialcheckable_p.h \
		lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialoverlaywidget.h \
		lib/qtmaterialripple.h \
		lib/qtmaterialstyle.h \
		lib/qtmaterialstyle_p.h \
		lib/qtmaterialcheckable_internal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialcheckable.o lib/qtmaterialcheckable.cpp

qtmaterialripple.o: lib/qtmaterialripple.cpp lib/qtmaterialripple.h \
		lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialoverlaywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialripple.o lib/qtmaterialripple.cpp

qtmaterialrippleoverlay.o: lib/qtmaterialrippleoverlay.cpp lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialoverlaywidget.h \
		lib/qtmaterialripple.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialrippleoverlay.o lib/qtmaterialrippleoverlay.cpp

qtmaterialstatetransition.o: lib/qtmaterialstatetransition.cpp lib/qtmaterialstatetransition.h \
		lib/qtmaterialstatetransitionevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialstatetransition.o lib/qtmaterialstatetransition.cpp

qtmaterialtextfield_internal.o: Admin_GUI/Widgets/qtmaterialtextfield_internal.cpp Admin_GUI/Widgets/qtmaterialtextfield_internal.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialtextfield_internal.o Admin_GUI/Widgets/qtmaterialtextfield_internal.cpp

qtmaterialtextfield.o: Admin_GUI/Widgets/qtmaterialtextfield.cpp Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtextfield_p.h \
		Admin_GUI/Widgets/qtmaterialtextfield_internal.h \
		lib/qtmaterialstyle.h \
		lib/qtmaterialstyle_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialtextfield.o Admin_GUI/Widgets/qtmaterialtextfield.cpp

qtmaterialtoggle_internal.o: Admin_GUI/Widgets/qtmaterialtoggle_internal.cpp Admin_GUI/Widgets/qtmaterialtoggle_internal.h \
		lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		lib/qtmaterialripple.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialtoggle_internal.o Admin_GUI/Widgets/qtmaterialtoggle_internal.cpp

qtmaterialtoggle.o: Admin_GUI/Widgets/qtmaterialtoggle.cpp Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Widgets/qtmaterialtoggle_p.h \
		Admin_GUI/Widgets/qtmaterialtoggle_internal.h \
		lib/qtmaterialrippleoverlay.h \
		lib/qtmaterialoverlaywidget.h \
		lib/qtmaterialstyle.h \
		lib/qtmaterialstyle_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialtoggle.o Admin_GUI/Widgets/qtmaterialtoggle.cpp

qtmaterialdialog_internal.o: Admin_GUI/Widgets/qtmaterialdialog_internal.cpp Admin_GUI/Widgets/qtmaterialdialog_internal.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialdialog_internal.o Admin_GUI/Widgets/qtmaterialdialog_internal.cpp

qtmaterialdialog.o: Admin_GUI/Widgets/qtmaterialdialog.cpp Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Widgets/qtmaterialdialog_p.h \
		Admin_GUI/Widgets/qtmaterialdialog_internal.h \
		lib/qtmaterialstatetransition.h \
		lib/qtmaterialstatetransitionevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmaterialdialog.o Admin_GUI/Widgets/qtmaterialdialog.cpp

filedialogwidget.o: Admin_GUI/Views/filedialogwidget.cpp Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedialogwidget.o Admin_GUI/Views/filedialogwidget.cpp

terminal.o: Services/terminal.cpp Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o terminal.o Services/terminal.cpp

fileexplorer.o: Services/fileexplorer.cpp Services/fileexplorer.h \
		Structs/programstruct.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileexplorer.o Services/fileexplorer.cpp

kioskservice.o: Services/kioskservice.cpp Services/kioskservice.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kioskservice.o Services/kioskservice.cpp

databaseservice.o: Services/databaseservice.cpp Services/databaseservice.h \
		Structs/userstruct.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databaseservice.o Services/databaseservice.cpp

linuxuserservice.o: Services/linuxuserservice.cpp Services/linuxuserservice.h \
		Services/terminal.h \
		Structs/userstruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linuxuserservice.o Services/linuxuserservice.cpp

identifyservice.o: Services/identifyservice.cpp Services/identifyservice.h \
		Services/terminal.h \
		Services/databaseservice.h \
		Structs/userstruct.h \
		Services/linuxuserservice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o identifyservice.o Services/identifyservice.cpp

toolbardisableservice.o: Services/toolbardisableservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbardisableservice.o Services/toolbardisableservice.cpp

desktoppanel.o: Admin_GUI/Views/desktoppanel.cpp Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Services/terminal.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktoppanel.o Admin_GUI/Views/desktoppanel.cpp

roleeditpanel.o: Admin_GUI/Views/roleeditpanel.cpp Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Services/terminal.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/startupdialogwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o roleeditpanel.o Admin_GUI/Views/roleeditpanel.cpp

additionalsettingspanel.o: Admin_GUI/Views/additionalsettingspanel.cpp Admin_GUI/Views/additionalsettingspanel.h \
		Services/linuxuserservice.h \
		Services/terminal.h \
		Structs/userstruct.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o additionalsettingspanel.o Admin_GUI/Views/additionalsettingspanel.cpp

userfileseditpanel.o: Admin_GUI/Views/userfileseditpanel.cpp Admin_GUI/Views/userfileseditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Services/terminal.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/startupdialogwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userfileseditpanel.o Admin_GUI/Views/userfileseditpanel.cpp

topbar.o: Admin_GUI/Views/topbar.cpp Admin_GUI/Views/topbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o topbar.o Admin_GUI/Views/topbar.cpp

startuppanel.o: Admin_GUI/Views/startuppanel.cpp Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Services/terminal.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startuppanel.o Admin_GUI/Views/startuppanel.cpp

filedelegate.o: Admin_GUI/Delegates/filedelegate.cpp Admin_GUI/Delegates/filedelegate.h \
		Structs/programstruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedelegate.o Admin_GUI/Delegates/filedelegate.cpp

admingui.o: Admin_GUI/Views/admingui.cpp Admin_GUI/Views/admingui.h \
		Services/databaseservice.h \
		Structs/userstruct.h \
		Services/terminal.h \
		Services/linuxuserservice.h \
		Admin_GUI/Model/usermodel.h \
		Admin_GUI/Views/topbar.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Delegates/userdelegate.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Views/settingspanel.h \
		Admin_GUI/Views/userinfopanel.h \
		Services/integrityservice.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		globalfunctions.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admingui.o Admin_GUI/Views/admingui.cpp

linuxuserslistwidget.o: Admin_GUI/Views/linuxuserslistwidget.cpp Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Delegates/userdelegate.h \
		Structs/userstruct.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Model/usermodel.h \
		Services/linuxuserservice.h \
		Services/terminal.h \
		Services/databaseservice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linuxuserslistwidget.o Admin_GUI/Views/linuxuserslistwidget.cpp

userinfopanel.o: Admin_GUI/Views/userinfopanel.cpp Admin_GUI/Views/userinfopanel.h \
		Structs/userstruct.h \
		Services/integrityservice.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userinfopanel.o Admin_GUI/Views/userinfopanel.cpp

usereditpanel.o: Admin_GUI/Views/usereditpanel.cpp Admin_GUI/Views/usereditpanel.h \
		Services/databaseservice.h \
		Structs/userstruct.h \
		Services/terminal.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usereditpanel.o Admin_GUI/Views/usereditpanel.cpp

settingspanel.o: Admin_GUI/Views/settingspanel.cpp Admin_GUI/Views/settingspanel.h \
		Admin_GUI/Views/userinfopanel.h \
		Structs/userstruct.h \
		Services/integrityservice.h \
		Services/terminal.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/databaseservice.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingspanel.o Admin_GUI/Views/settingspanel.cpp

startuprepositoryservice.o: Services/startuprepositoryservice.cpp Services/startuprepositoryservice.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startuprepositoryservice.o Services/startuprepositoryservice.cpp

startuprunnableservice.o: Services/startuprunnableservice.cpp Services/startuprunnableservice.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startuprunnableservice.o Services/startuprunnableservice.cpp

messagesrepository.o: Server/messagesrepository.cpp Server/messagesrepository.h \
		Server/DataMessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messagesrepository.o Server/messagesrepository.cpp

dataHandler.o: Server/dataHandler.cpp Server/dataHandler.h \
		Server/messagesrepository.h \
		Server/DataMessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataHandler.o Server/dataHandler.cpp

program.o: program.cpp program.h \
		Services/appsettingsservice.h \
		globalfunctions.h \
		Services/terminal.h \
		Services/identifyservice.h \
		Services/databaseservice.h \
		Structs/userstruct.h \
		Services/linuxuserservice.h \
		Services/toolbardisableservice.h \
		Services/startuprunnableservice.h \
		Server/dataHandler.h \
		Server/messagesrepository.h \
		Server/DataMessage.h \
		Admin_GUI/Views/admingui.h \
		Admin_GUI/Model/usermodel.h \
		Admin_GUI/Views/topbar.h \
		Admin_GUI/Views/linuxuserslistwidget.h \
		Admin_GUI/Delegates/userdelegate.h \
		Admin_GUI/Model/sortmodel.h \
		Admin_GUI/Views/settingspanel.h \
		Admin_GUI/Views/userinfopanel.h \
		Services/integrityservice.h \
		Admin_GUI/Views/usereditpanel.h \
		Services/kioskservice.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h \
		Admin_GUI/Widgets/qtmaterialtoggle.h \
		Admin_GUI/Views/qtoast.h \
		Admin_GUI/Views/additionalsettingspanel.h \
		Admin_GUI/Views/roleeditpanel.h \
		Admin_GUI/Views/desktoppanel.h \
		Structs/programstruct.h \
		Services/fileexplorer.h \
		Admin_GUI/Delegates/filedelegate.h \
		Admin_GUI/Widgets/qtmaterialdialog.h \
		lib/qtmaterialoverlaywidget.h \
		Admin_GUI/Views/filedialogwidget.h \
		Admin_GUI/Views/startuppanel.h \
		Services/startuprepositoryservice.h \
		Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Views/userfileseditpanel.h \
		User_GUI/User_GUI.h \
		Styles/framelesswindow.h \
		Styles/windowdragger.h \
		Styles/darkstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o program.cpp

startupdialogwidget.o: Admin_GUI/Views/startupdialogwidget.cpp Admin_GUI/Views/startupdialogwidget.h \
		Admin_GUI/Widgets/qtmaterialtextfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startupdialogwidget.o Admin_GUI/Views/startupdialogwidget.cpp

popupdialog.o: Admin_GUI/Widgets/popupdialog.cpp Admin_GUI/Widgets/popupdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o popupdialog.o Admin_GUI/Widgets/popupdialog.cpp

globalfunctions.o: globalfunctions.cpp globalfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globalfunctions.o globalfunctions.cpp

appsettingsservice.o: Services/appsettingsservice.cpp Services/appsettingsservice.h \
		globalfunctions.h \
		Services/terminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appsettingsservice.o Services/appsettingsservice.cpp

darkstyle.o: Styles/darkstyle.cpp Styles/darkstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o darkstyle.o Styles/darkstyle.cpp

framelesswindow.o: Styles/framelesswindow.cpp Styles/framelesswindow.h \
		Styles/windowdragger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framelesswindow.o Styles/framelesswindow.cpp

windowdragger.o: Styles/windowdragger.cpp Styles/windowdragger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o windowdragger.o Styles/windowdragger.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_User_GUI.o: moc_User_GUI.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_User_GUI.o moc_User_GUI.cpp

moc_usermodel.o: moc_usermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usermodel.o moc_usermodel.cpp

moc_sortmodel.o: moc_sortmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sortmodel.o moc_sortmodel.cpp

moc_qtoast.o: moc_qtoast.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtoast.o moc_qtoast.cpp

moc_qtmaterialstyle.o: moc_qtmaterialstyle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialstyle.o moc_qtmaterialstyle.cpp

moc_qtmaterialtheme.o: moc_qtmaterialtheme.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialtheme.o moc_qtmaterialtheme.cpp

moc_qtmaterialoverlaywidget.o: moc_qtmaterialoverlaywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialoverlaywidget.o moc_qtmaterialoverlaywidget.cpp

moc_qtmaterialcheckable_internal.o: moc_qtmaterialcheckable_internal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialcheckable_internal.o moc_qtmaterialcheckable_internal.cpp

moc_qtmaterialripple.o: moc_qtmaterialripple.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialripple.o moc_qtmaterialripple.cpp

moc_qtmaterialrippleoverlay.o: moc_qtmaterialrippleoverlay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialrippleoverlay.o moc_qtmaterialrippleoverlay.cpp

moc_qtmaterialcheckable.o: moc_qtmaterialcheckable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialcheckable.o moc_qtmaterialcheckable.cpp

moc_qtmaterialstatetransition.o: moc_qtmaterialstatetransition.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialstatetransition.o moc_qtmaterialstatetransition.cpp

moc_qtmaterialtextfield_internal.o: moc_qtmaterialtextfield_internal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialtextfield_internal.o moc_qtmaterialtextfield_internal.cpp

moc_qtmaterialtextfield.o: moc_qtmaterialtextfield.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialtextfield.o moc_qtmaterialtextfield.cpp

moc_qtmaterialtoggle_internal.o: moc_qtmaterialtoggle_internal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialtoggle_internal.o moc_qtmaterialtoggle_internal.cpp

moc_qtmaterialtoggle.o: moc_qtmaterialtoggle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialtoggle.o moc_qtmaterialtoggle.cpp

moc_qtmaterialdialog_internal.o: moc_qtmaterialdialog_internal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialdialog_internal.o moc_qtmaterialdialog_internal.cpp

moc_qtmaterialdialog.o: moc_qtmaterialdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtmaterialdialog.o moc_qtmaterialdialog.cpp

moc_filedialogwidget.o: moc_filedialogwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedialogwidget.o moc_filedialogwidget.cpp

moc_desktoppanel.o: moc_desktoppanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desktoppanel.o moc_desktoppanel.cpp

moc_roleeditpanel.o: moc_roleeditpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_roleeditpanel.o moc_roleeditpanel.cpp

moc_additionalsettingspanel.o: moc_additionalsettingspanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_additionalsettingspanel.o moc_additionalsettingspanel.cpp

moc_userfileseditpanel.o: moc_userfileseditpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userfileseditpanel.o moc_userfileseditpanel.cpp

moc_topbar.o: moc_topbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_topbar.o moc_topbar.cpp

moc_startuppanel.o: moc_startuppanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startuppanel.o moc_startuppanel.cpp

moc_admingui.o: moc_admingui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admingui.o moc_admingui.cpp

moc_linuxuserslistwidget.o: moc_linuxuserslistwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_linuxuserslistwidget.o moc_linuxuserslistwidget.cpp

moc_userinfopanel.o: moc_userinfopanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userinfopanel.o moc_userinfopanel.cpp

moc_usereditpanel.o: moc_usereditpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usereditpanel.o moc_usereditpanel.cpp

moc_settingspanel.o: moc_settingspanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingspanel.o moc_settingspanel.cpp

moc_startuprunnableservice.o: moc_startuprunnableservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startuprunnableservice.o moc_startuprunnableservice.cpp

moc_dataHandler.o: moc_dataHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataHandler.o moc_dataHandler.cpp

moc_program.o: moc_program.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_program.o moc_program.cpp

moc_startupdialogwidget.o: moc_startupdialogwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startupdialogwidget.o moc_startupdialogwidget.cpp

moc_popupdialog.o: moc_popupdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_popupdialog.o moc_popupdialog.cpp

moc_darkstyle.o: moc_darkstyle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_darkstyle.o moc_darkstyle.cpp

moc_framelesswindow.o: moc_framelesswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_framelesswindow.o moc_framelesswindow.cpp

moc_windowdragger.o: moc_windowdragger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_windowdragger.o moc_windowdragger.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

